OCP_CABLE_DEFAULTS = {
    15: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "12",
        "wire_ground_size": "12",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "2",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 25,
        "base_wire_x_per_1000ft": 0.068,
        "base_wire_r_per_1000ft": 2.0
    },
    20: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "12",
        "wire_ground_size": "12",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "2",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 25,
        "base_wire_x_per_1000ft": 0.068,
        "base_wire_r_per_1000ft": 2.0
    },
    25: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "10",
        "wire_ground_size": "10",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "2",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 35,
        "base_wire_x_per_1000ft": 0.063,
        "base_wire_r_per_1000ft": 1.2
    },
    30: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "10",
        "wire_ground_size": "10",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "2",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 35,
        "base_wire_x_per_1000ft": 0.063,
        "base_wire_r_per_1000ft": 1.2
    },
    35: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "8",
        "wire_ground_size": "10",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "1/0",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 50,
        "base_wire_x_per_1000ft": 0.065,
        "base_wire_r_per_1000ft": 0.78
    },
    40: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "8",
        "wire_ground_size": "10",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "1/0",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 50,
        "base_wire_x_per_1000ft": 0.065,
        "base_wire_r_per_1000ft": 0.78
    },
    45: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "8",
        "wire_ground_size": "10",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "1/0",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 50,
        "base_wire_x_per_1000ft": 0.065,
        "base_wire_r_per_1000ft": 0.78
    },
    50: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "8",
        "wire_ground_size": "10",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "1/0",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 50,
        "base_wire_x_per_1000ft": 0.065,
        "base_wire_r_per_1000ft": 0.78
    },
    60: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "6",
        "wire_ground_size": "10",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "1/0",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 65,
        "base_wire_x_per_1000ft": 0.064,
        "base_wire_r_per_1000ft": 0.49
    },
    70: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "4",
        "wire_ground_size": "8",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "1/0",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 85,
        "base_wire_x_per_1000ft": 0.06,
        "base_wire_r_per_1000ft": 0.31
    },
    80: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "4",
        "wire_ground_size": "8",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "1/0",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 85,
        "base_wire_x_per_1000ft": 0.06,
        "base_wire_r_per_1000ft": 0.31
    },
    90: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "2",
        "wire_ground_size": "8",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "350",
        "max_lug_qty": 1,
        "base_wire_ampacity_30deg": 115,
        "base_wire_x_per_1000ft": 0.057,
        "base_wire_r_per_1000ft": 0.2
    },
    100: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "2",
        "wire_ground_size": "8",
        "wire_service_ground_size": "8",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "350",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 115,
        "base_wire_x_per_1000ft": 0.057,
        "base_wire_r_per_1000ft": 0.2
    },
    110: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "2",
        "wire_ground_size": "6",
        "wire_service_ground_size": "6",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "350",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 115,
        "base_wire_x_per_1000ft": 0.057,
        "base_wire_r_per_1000ft": 0.2
    },
    125: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "1",
        "wire_ground_size": "6",
        "wire_service_ground_size": "6",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "350",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 130,
        "base_wire_x_per_1000ft": 0.057,
        "base_wire_r_per_1000ft": 0.16
    },
    150: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "1/0",
        "wire_ground_size": "6",
        "wire_service_ground_size": "6",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "350",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 150,
        "base_wire_x_per_1000ft": 0.044,
        "base_wire_r_per_1000ft": 0.12
    },
    175: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "2/0",
        "wire_ground_size": "6",
        "wire_service_ground_size": "4",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "350",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 175,
        "base_wire_x_per_1000ft": 0.043,
        "base_wire_r_per_1000ft": 0.1
    },
    200: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "3/0",
        "wire_ground_size": "6",
        "wire_service_ground_size": "4",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "350",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 200,
        "base_wire_x_per_1000ft": 0.042,
        "base_wire_r_per_1000ft": 0.077
    },
    225: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "4/0",
        "wire_ground_size": "4",
        "wire_service_ground_size": "2",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "350",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 230,
        "base_wire_x_per_1000ft": 0.041,
        "base_wire_r_per_1000ft": 0.062
    },
    250: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "250",
        "wire_ground_size": "4",
        "wire_service_ground_size": "2",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "500",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 255,
        "base_wire_x_per_1000ft": 0.041,
        "base_wire_r_per_1000ft": 0.052
    },
    300: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "350",
        "wire_ground_size": "4",
        "wire_service_ground_size": "2",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "600",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 310,
        "base_wire_x_per_1000ft": 0.04,
        "base_wire_r_per_1000ft": 0.038
    },
    350: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 1,
        "wire_hot_size": "500",
        "wire_ground_size": "3",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "600",
        "max_lug_qty": 2,
        "base_wire_ampacity_30deg": 380,
        "base_wire_x_per_1000ft": 0.039,
        "base_wire_r_per_1000ft": 0.027
    },
    400: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 2,
        "wire_hot_size": "3/0",
        "wire_ground_size": "3",
        "wire_service_ground_size": "4",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "600",
        "max_lug_qty": 3,
        "base_wire_ampacity_30deg": 200,
        "base_wire_x_per_1000ft": 0.042,
        "base_wire_r_per_1000ft": 0.077
    },
    450: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 2,
        "wire_hot_size": "4/0",
        "wire_ground_size": "2",
        "wire_service_ground_size": "2",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "600",
        "max_lug_qty": 3,
        "base_wire_ampacity_30deg": 230,
        "base_wire_x_per_1000ft": 0.041,
        "base_wire_r_per_1000ft": 0.062
    },
    500: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 2,
        "wire_hot_size": "250",
        "wire_ground_size": "2",
        "wire_service_ground_size": "2",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "600",
        "max_lug_qty": 3,
        "base_wire_ampacity_30deg": 255,
        "base_wire_x_per_1000ft": 0.041,
        "base_wire_r_per_1000ft": 0.052
    },
    600: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 2,
        "wire_hot_size": "350",
        "wire_ground_size": "1",
        "wire_service_ground_size": "2",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "600",
        "max_lug_qty": 3,
        "base_wire_ampacity_30deg": 310,
        "base_wire_x_per_1000ft": 0.04,
        "base_wire_r_per_1000ft": 0.038
    },
    700: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 2,
        "wire_hot_size": "500",
        "wire_ground_size": "1/0",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "600",
        "max_lug_qty": 3,
        "base_wire_ampacity_30deg": 380,
        "base_wire_x_per_1000ft": 0.039,
        "base_wire_r_per_1000ft": 0.027
    },
    800: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 2,
        "wire_hot_size": "500",
        "wire_ground_size": "1/0",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Magnetic",
        "conduit_type": "EMT",
        "max_lug_size": "600",
        "max_lug_qty": 4,
        "base_wire_ampacity_30deg": 380,
        "base_wire_x_per_1000ft": 0.039,
        "base_wire_r_per_1000ft": 0.027
    },
    1000: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 3,
        "wire_hot_size": "400",
        "wire_ground_size": "2/0",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Non-Magnetic",
        "conduit_type": "PVC",
        "max_lug_size": "600",
        "max_lug_qty": 4,
        "base_wire_ampacity_30deg": 335,
        "base_wire_x_per_1000ft": 0.04,
        "base_wire_r_per_1000ft": 0.033
    },
    1200: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 3,
        "wire_hot_size": "600",
        "wire_ground_size": "3/0",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Non-Magnetic",
        "conduit_type": "PVC",
        "max_lug_size": "600",
        "max_lug_qty": 4,
        "base_wire_ampacity_30deg": 420,
        "base_wire_x_per_1000ft": 0.039,
        "base_wire_r_per_1000ft": 0.023
    },
    1600: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 4,
        "wire_hot_size": "600",
        "wire_ground_size": "4/0",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Non-Magnetic",
        "conduit_type": "PVC",
        "max_lug_size": "600",
        "max_lug_qty": 6,
        "base_wire_ampacity_30deg": 420,
        "base_wire_x_per_1000ft": 0.039,
        "base_wire_r_per_1000ft": 0.023
    },
    2000: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 5,
        "wire_hot_size": "600",
        "wire_ground_size": "250",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Non-Magnetic",
        "conduit_type": "PVC",
        "max_lug_size": "600",
        "max_lug_qty": 8,
        "base_wire_ampacity_30deg": 420,
        "base_wire_x_per_1000ft": 0.039,
        "base_wire_r_per_1000ft": 0.023
    },
    2500: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 6,
        "wire_hot_size": "600",
        "wire_ground_size": "350",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Non-Magnetic",
        "conduit_type": "PVC",
        "max_lug_size": "750",
        "max_lug_qty": 15,
        "base_wire_ampacity_30deg": 420,
        "base_wire_x_per_1000ft": 0.039,
        "base_wire_r_per_1000ft": 0.023
    },
    3000: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 8,
        "wire_hot_size": "500",
        "wire_ground_size": "400",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Non-Magnetic",
        "conduit_type": "PVC",
        "max_lug_size": "750",
        "max_lug_qty": 15,
        "base_wire_ampacity_30deg": 380,
        "base_wire_x_per_1000ft": 0.039,
        "base_wire_r_per_1000ft": 0.027
    },
    4000: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 10,
        "wire_hot_size": "600",
        "wire_ground_size": "500",
        "wire_service_ground_size": "1/0",
        "conduit_material_type": "Non-Magnetic",
        "conduit_type": "PVC",
        "max_lug_size": "750",
        "max_lug_qty": 15,
        "base_wire_ampacity_30deg": 420,
        "base_wire_x_per_1000ft": 0.039,
        "base_wire_r_per_1000ft": 0.023
    },
    5000: {
        "wire_material": "CU",
        "wire_temperature_rating": "75 C",
        "wire_insulation": "THWN",
        "number_of_parallel_sets": 11,
        "wire_hot_size": "750",
        "wire_ground_size": "700",
        "wire_service_ground_size": "2/0",
        "conduit_material_type": "Non-Magnetic",
        "conduit_type": "PVC",
        "max_lug_size": "750",
        "max_lug_qty": 15,
        "base_wire_ampacity_30deg": 475,
        "base_wire_x_per_1000ft": 0.038,
        "base_wire_r_per_1000ft": 0.019
    }
}